-- Dark Legacy — Multi-stat Personal Events
-- Autonomous personal events that leverage wild attributes and personality combos.

return {
    {
        id = "blood_thunder_rage",
        title = "Blood and Thunder",
        narrative = "{heir_name}'s fury erupts without warning. Furniture splinters. Servants flee. The rage is absolute.",
        trigger_axis = "PER_VOL",
        trigger_min = 70,
        chance = 0.35,
        cooldown = 6,
        consequence = {
            cultural_memory_shift = { physical = 3, social = -2 },
            narrative = "The rage passes, leaving destruction and fear in its wake. {heir_name} stands amid the wreckage, breathing hard.",
        },
    },
    {
        id = "silver_tongue_deal",
        title = "Words Like Honey",
        narrative = "{heir_name} talks a hostile merchant into selling goods at half price — and thanking the family for the privilege.",
        trigger_axis = "PER_CUR",
        trigger_min = 55,
        chance = 0.3,
        cooldown = 6,
        consequence = {
            cultural_memory_shift = { social = 3 },
            narrative = "The merchant departs smiling, not realizing until later what happened. {heir_name}'s reputation grows.",
        },
    },
    {
        id = "obsessive_research",
        title = "The Night Scholar",
        narrative = "{heir_name} hasn't slept in days. The study is littered with notes. Something is being unraveled.",
        trigger_axis = "PER_OBS",
        trigger_min = 70,
        chance = 0.3,
        cooldown = 8,
        consequence = {
            cultural_memory_shift = { mental = 4, social = -1 },
            narrative = "When {heir_name} finally emerges, there is a new light in those sleepless eyes. Something has been understood.",
        },
    },
    {
        id = "pride_monument",
        title = "A Statue for the Ages",
        narrative = "{heir_name} commissions a massive statue of the family founder. It must be seen from every corner of the domain.",
        trigger_axis = "PER_PRI",
        trigger_min = 70,
        chance = 0.25,
        cooldown = 10,
        consequence = {
            cultural_memory_shift = { creative = 2, social = 1 },
            faction_power_shift = 3,
            narrative = "The statue rises, absurd in its grandeur. But somehow... it inspires. The people look up at it and feel something.",
        },
    },
    {
        id = "merciful_pardon",
        title = "The Unexpected Pardon",
        narrative = "A condemned prisoner begs {heir_name} for mercy. To everyone's shock, it is granted.",
        trigger_axis = "PER_CRM",
        trigger_max = 30,
        chance = 0.3,
        cooldown = 6,
        consequence = {
            cultural_memory_shift = { social = 3 },
            disposition_changes = { { faction_id = "all", delta = 5 } },
            narrative = "The pardoned prisoner vanishes. Years later, a mysterious benefactor aids the family. Mercy has long arms.",
        },
    },
    {
        id = "loyal_sacrifice",
        title = "Blood for Blood",
        narrative = "{heir_name} rushes into a burning building to save a trapped servant. No calculation. Just instinct.",
        trigger_axis = "PER_LOY",
        trigger_min = 75,
        chance = 0.25,
        cooldown = 8,
        consequence = {
            cultural_memory_shift = { social = 3, physical = 1 },
            narrative = "Both survive, barely. The household whispers in awe. {heir_name} bears the scars without complaint.",
        },
    },
    {
        id = "adaptive_reinvention",
        title = "The Chameleon",
        narrative = "{heir_name} abandons a failing strategy mid-execution and improvises something entirely new. It shouldn't work. It does.",
        trigger_axis = "PER_ADA",
        trigger_min = 70,
        chance = 0.3,
        cooldown = 6,
        consequence = {
            cultural_memory_shift = { creative = 2, mental = 2 },
            narrative = "The improvisation succeeds against all odds. {heir_name}'s flexibility is as terrifying as any sword.",
        },
    },
    {
        id = "cruel_efficiency",
        title = "The Necessary Cut",
        narrative = "{heir_name} orders the execution of a popular but ineffective advisor. No trial. No warning.",
        trigger_axis = "PER_CRM",
        trigger_min = 70,
        chance = 0.25,
        cooldown = 8,
        consequence = {
            cultural_memory_shift = { social = -2 },
            disposition_changes = { { faction_id = "all", delta = -3 } },
            narrative = "Efficiency improves immediately. But the household sleeps less soundly now.",
        },
    },
    {
        id = "cautious_retreat",
        title = "Discretion Over Valor",
        narrative = "{heir_name} orders a full retreat when scouts report an ambush ahead. The army grumbles.",
        trigger_axis = "PER_BLD",
        trigger_max = 25,
        chance = 0.3,
        cooldown = 6,
        consequence = {
            cultural_memory_shift = { mental = 2 },
            narrative = "The ambush is confirmed days later. The cautious retreat saved hundreds. Grumbling turns to grudging respect.",
        },
    },
    {
        id = "inventive_solution",
        title = "The Tinkerer's Triumph",
        narrative = "{heir_name} spends weeks in the workshop, emerging with a device no one has seen before.",
        trigger_axis = "PER_CUR",
        trigger_min = 65,
        chance = 0.25,
        cooldown = 8,
        consequence = {
            cultural_memory_shift = { creative = 4 },
            narrative = "The device works — imperfectly, but it works. A seed of innovation planted in the family's soil.",
        },
    },
}
