-- Dark Legacy — Council Action Definitions
-- One strategic action per generation. Personality-gated.
-- Pure data, no logic.

return {
    -- ─── DIPLOMACY ──────────────────────────────────────────────────────────
    {
        id = "seek_alliance",
        category = "diplomacy",
        label = "Forge a Blood-Oath",
        description = "Send envoys to a rival house with gifts of gold and promises of shared fate. Softens hearts and opens borders.",
        requires = nil, 
        requires_no_condition = "war",
        requires_gold_min = 15,
        requires_target_faction = true,
        narrative = "Envoys were dispatched bearing heavy coffers and honeyed words. The seeds of a shared future were sown.",
        consequences = {
            disposition_changes = { { faction_id = "_target", delta = 20 } },
            cultural_memory_shift = { social = 3 },
            resource_change = { type = "gold", delta = -15, reason = "Diplomatic tribute" },
            moral_act = { act_id = "diplomacy", description = "Forged a blood-oath with a rival house" },
        },
    },
    {
        id = "declare_rivalry",
        category = "diplomacy",
        label = "Public Denunciation",
        description = "Formally mark a house as your bloodline's nemesis. Fuels the family's pride but invites immediate hostility.",
        requires = { axis = "PER_BLD", min = 40 },
        requires_disposition_max = 45,
        requires_target_faction = true,
        narrative = "The declaration was read in the high court. A line was drawn in the ash. The world knows our enemy.",
        consequences = {
            disposition_changes = { { faction_id = "_target", delta = -30 } },
            add_relationship = { type = "enemy", strength = 75, reason = "public_denunciation" },
            cultural_memory_shift = { physical = 2, social = -2 },
            lineage_power_shift = 10,
        },
    },

    {
        id = "atone",
        category = "diplomacy",
        label = "Public Atonement",
        description = "The heir kneels before the court and the common folk, confessing the bloodline's sins. Gold is given freely. Pride is surrendered.",
        requires = { axis = "PER_CRM", max = 55 },
        personality_blocks = {
            { axis = "PER_PRI", min = 80, reason = "Too proud to kneel before anyone." },
            { axis = "PER_CRM", min = 75, reason = "The cruel do not repent." },
        },
        requires_gold_min = 10,
        requires_target_faction = false,
        narrative = "The heir knelt in the dirt before the assembled world and spoke of every wrong the bloodline had done. Some wept. Some laughed. All remembered.",
        consequences = {
            moral_act = { act_id = "sacrifice", description = "Publicly atoned for the bloodline's sins" },
            cultural_memory_shift = { social = 3 },
            resource_change = { type = "gold", delta = -10, reason = "Reparations and alms" },
            disposition_changes = { { faction_id = "all", delta = 5 } },
            lineage_power_shift = -5,
        },
    },

    -- ─── WARFARE ────────────────────────────────────────────────────────────
    {
        id = "purge_the_weak",
        category = "warfare",
        label = "The Iron Culling",
        description = "Exile or execute the infirm and the hesitant. Hardens the bloodline but leaves deep scars in the family's soul.",
        requires = { axis = "PER_CRM", min = 60 },
        personality_blocks = {
            { axis = "PER_LOY", min = 80, reason = "Too loyal to betray their own kin." },
        },
        blocked_by_taboo = "will_never_repeat_cruelty",
        requires_target_faction = false,
        narrative = "The weak were cast out into the waste. Those who remain are harder, colder, and fewer.",
        consequences = {
            cultural_memory_shift = { physical = 5, social = -8 },
            disposition_changes = { { faction_id = "all", delta = -6 } },
            mutation_triggers = { { type = "war", intensity = 0.3 } },
            lineage_power_shift = 15,
            moral_act = { act_id = "cruelty", description = "Purged the weak from the bloodline" },
        },
    },
    {
        id = "fortify_border",
        category = "warfare",
        label = "Raise the Ash-Walls",
        description = "Pour steel and labor into defensive works. Protects against external threats but drains the treasury.",
        requires = { axis = "PER_OBS", min = 40 },
        requires_gold_min = 20,
        requires_steel_min = 10,
        requires_target_faction = false,
        narrative = "The hammers never stopped. New ramparts of cold iron now shadow the pass.",
        consequences = {
            cultural_memory_shift = { physical = 3, mental = 1 },
            resource_change = { 
                { type = "gold", delta = -20, reason = "Masonry and labor" },
                { type = "steel", delta = -10, reason = "Reinforcing the gates" }
            },
            lineage_power_shift = 12,
        },
    },

    -- ─── INTRIGUE ───────────────────────────────────────────────────────────
    {
        id = "send_scouts",
        category = "intrigue",
        label = "Shadow-Eyes Initiative",
        description = "Dispatch masked agents to infiltrate a rival's holdings. Knowledge is the only true shield.",
        requires = { axis = "PER_CUR", min = 40 },
        requires_target_faction = true,
        narrative = "Our agents moved through the cracks in the world. They return with secrets that could topple towers.",
        consequences = {
            reveal_faction_info = true,
            cultural_memory_shift = { mental = 3, social = -1 },
        },
    },
    {
        id = "spread_rumors",
        category = "intrigue",
        label = "Poison the Well",
        description = "Whisper lies and half-truths about a rival's lineage. Destroys their reputation without shedding a drop of blood.",
        requires = { axis = "PER_ADA", min = 50 },
        personality_blocks = {
            { axis = "PER_LOY", min = 80, reason = "Too honorable to deal in lies." },
        },
        blocked_by_taboo = "will_never_repeat_cruelty",
        requires_target_faction = true,
        stat_check = { primary = { trait = "SOC_INF", weight = 1.0 }, secondary = { trait = "SOC_DEP", weight = 0.5 }, difficulty = 35 },
        narrative = "The seeds of doubt were sown in every tavern and court. Their name is now a curse.",
        consequences = {
            disposition_changes = { { faction_id = "_target", delta = -15 }, { faction_id = "all", delta = -3 } },
            cultural_memory_shift = { mental = 2, social = 2 },
            moral_act = { act_id = "exploitation", description = "Spread lies to destroy a rival's reputation" },
        },
        consequences_fail = {
            narrative = "The rumors were traced back to our court. The lie exposed, the liar revealed.",
            disposition_changes = { { faction_id = "_target", delta = -25 }, { faction_id = "all", delta = -8 } },
            cultural_memory_shift = { social = -4 },
            moral_act = { act_id = "exploitation", description = "Caught spreading lies about a rival house" },
            lineage_power_shift = -8,
        },
    },

    -- ─── LEGACY ─────────────────────────────────────────────────────────────
    {
        id = "develop_holding",
        category = "legacy",
        label = "Pour Into the Foundation",
        description = "Invest in one of the bloodline's holdings, increasing its size and yields. A long-term investment in prosperity.",
        requires = { axis = "PER_OBS", min = 40 },
        requires_gold_min = 25,
        requires_target_holding = true,
        narrative = "Laborers and materials were sent to the chosen domain. It grows, its future secured by today's sacrifice.",
        consequences = {
            holding_size_increase = { amount = 1 },
            resource_change = { type = "gold", delta = -25, reason = "Domain development" },
            cultural_memory_shift = { creative = 2, mental = 1 },
        },
    },
    {
        id = "invest_next_gen",
        category = "legacy",
        label = "The Debt of Tutelage",
        description = "Dedicate vast resources to the education of the future heir. Shapes their mind and soul before they take the throne.",
        requires = nil,
        requires_gold_min = 15,
        requires_target_faction = false,
        requires_category_choice = true,
        narrative = "The best tutors and most ancient scrolls were gathered. The future is being written in the heart of a child.",
        consequences = {
            offspring_boost = { amount = 10 },
            cultural_memory_shift_chosen = 5,
            resource_change = { type = "gold", delta = -15, reason = "Tutors and training" },
        },
    },
    {
        id = "commission_great_work",
        category = "legacy",
        label = "The Vanity of Stone",
        description = "Begin a massive project—a library, a statue, or a cathedral—to cement the family's name in history.",
        requires = { axis = "PER_PRI", min = 40 },
        requires_gold_min = 25,
        system_action = "start_great_work",
        stat_check = { primary = { trait = "CRE_AES", weight = 1.0 }, secondary = { trait = "SOC_INF", weight = 0.5 }, difficulty = 55 },
        narrative = "Foundation stones were laid. A project that will span generations has begun.",
        consequences = {
            cultural_memory_shift = { creative = 5 },
            disposition_changes = { { faction_id = "all", delta = 5 } },
            resource_change = { type = "gold", delta = -25, reason = "Great Work funding" },
            lineage_power_shift = 10,
        },
        consequences_fail = {
            narrative = "The foundations cracked before the first winter. The heir's vision outstripped their ability to execute it.",
            resource_change = { type = "gold", delta = -15, reason = "Wasted construction" },
            lineage_power_shift = -5,
            disposition_changes = { { faction_id = "all", delta = -3 } },
        },
    },

    -- ─── DIPLOMACY (continued) ────────────────────────────────────────────
    {
        id = "diplomatic_marriage",
        category = "diplomacy",
        label = "Dynastic Betrothal",
        description = "Offer a lesser member of the house in marriage to a rival faction. Improves relations at the cost of gold and a piece of the family's independence.",
        requires = { axis = "PER_LOY", min = 35 },
        requires_gold_min = 10,
        requires_target_faction = true,
        requires_generation_min = 3,
        system_action = "diplomatic_marriage",
        narrative = "The betrothal was sealed in ink and blood. Two houses are now bound by a shared future.",
        consequences = {
            disposition_changes = { { faction_id = "_target", delta = 25 } },
            cultural_memory_shift = { social = 3 },
            resource_change = { type = "gold", delta = -10, reason = "Dowry and wedding feast" },
        },
    },
    {
        id = "trade_agreement",
        category = "diplomacy",
        label = "The Binding Ledger",
        description = "Negotiate a commerce pact with a rival house. Fills the coffers but creates dependency. Requires initial investment.",
        requires = { axis = "PER_ADA", min = 35 },
        requires_gold_min = 8,
        requires_target_faction = true,
        narrative = "The trade wagons roll. Gold flows both ways, and with it, obligation.",
        consequences = {
            disposition_changes = { { faction_id = "_target", delta = 10 } },
            resource_change = {
                { type = "gold", delta = 8, reason = "Trade revenue (net after investment)" },
                { type = "grain", delta = 4, reason = "Imported goods" },
            },
            cultural_memory_shift = { social = 2 },
        },
    },
    {
        id = "negotiate_shadow",
        category = "diplomacy",
        label = "Parley with Exiles",
        description = "Reach out to a shadow lineage — the lost branches of your own blood. They may return, or they may remember why they left.",
        requires = { axis = "PER_LOY", min = 45 },
        requires_gold_min = 10,
        requires_generation_min = 5,
        system_action = "negotiate_shadow",
        narrative = "A message was sent into the waste. The exiles read it by firelight and debated through the night.",
        consequences = {
            resource_change = { type = "gold", delta = -10, reason = "Gifts to the exiled branch" },
            cultural_memory_shift = { social = 3, mental = 1 },
        },
    },

    -- ─── WARFARE (continued) ──────────────────────────────────────────────
    {
        id = "launch_campaign",
        category = "warfare",
        label = "March to War",
        description = "Launch a military campaign against a rival house. Victory brings spoils and dominance. Defeat brings ruin.",
        requires = { axis = "PER_BLD", min = 55 },
        personality_blocks = {
            { axis = "PER_ADA", min = 85, reason = "Too adaptable to commit to a single front." },
        },
        requires_steel_min = 15,
        requires_gold_min = 10,
        requires_target_faction = true,
        requires_disposition_max = 35,
        system_action = "start_campaign",
        stat_check = { primary = { trait = "PHY_STR", weight = 1.0 }, secondary = { trait = "MEN_STR", weight = 0.5 }, difficulty = 55 },
        narrative = "The banners were raised. The bloodline marches to war.",
        consequences = {
            cultural_memory_shift = { physical = 5, social = -3 },
            resource_change = {
                { type = "steel", delta = -15, reason = "Arming the host" },
                { type = "gold", delta = -10, reason = "War wages" },
            },
            mutation_triggers = { { type = "war", intensity = 0.4 } },
        },
        consequences_fail = {
            narrative = "The campaign preparations faltered. The heir's weakness was exposed before the march could begin.",
            cultural_memory_shift = { physical = -2, social = -4 },
            resource_change = {
                { type = "steel", delta = -8, reason = "Wasted preparations" },
                { type = "gold", delta = -10, reason = "War wages (squandered)" },
            },
            lineage_power_shift = -10,
        },
    },

    {
        id = "conscript_levies",
        category = "warfare",
        label = "Bleed the Holdings Dry",
        description = "Call upon every holding to send soldiers and supplies. Drains the domains but fills the bloodline's war chest.",
        requires = { axis = "PER_BLD", min = 40 },
        requires_holdings_min = 2,
        requires_target_faction = false,
        system_action = "conscript_levies",
        narrative = "Every village, mine, and fortress was bled for men and materiel. The domains grow thin, but the armory is full.",
        consequences = {
            cultural_memory_shift = { physical = 3, social = -2 },
        },
    },
    {
        id = "post_bounty",
        category = "warfare",
        label = "Mark for Death",
        description = "Place a blood-price on the head of a rival house's heir. Assassins will do what armies cannot.",
        requires = { axis = "PER_CRM", min = 50 },
        personality_blocks = {
            { axis = "PER_LOY", min = 85, reason = "Honor forbids assassination." },
        },
        requires_gold_min = 20,
        requires_target_faction = true,
        blocked_by_taboo = "will_never_repeat_cruelty",
        system_action = "post_bounty",
        stat_check = { primary = { trait = "SOC_INF", weight = 1.0 }, secondary = { trait = "MEN_PER", weight = 0.5 }, difficulty = 45 },
        narrative = "The contract was signed in red ink. Somewhere in the world, a killer reads the name.",
        consequences = {
            resource_change = { type = "gold", delta = -20, reason = "Assassination bounty" },
            cultural_memory_shift = { physical = 1, social = -3 },
            moral_act = { act_id = "assassination", description = "Put a bounty on a rival heir's head" },
        },
        consequences_fail = {
            narrative = "The assassins took the gold and vanished. The target lives. Worse — they know who sent the killers.",
            resource_change = { type = "gold", delta = -20, reason = "Bounty paid (wasted)" },
            cultural_memory_shift = { social = -5 },
            moral_act = { act_id = "assassination", description = "Botched assassination attempt" },
        },
    },
    {
        id = "reinforce_campaign",
        category = "warfare",
        label = "Feed the War Machine",
        description = "Pour fresh steel and gold into an active military campaign. Shifts the tide, but at terrible cost.",
        requires = { axis = "PER_BLD", min = 40 },
        requires_steel_min = 10,
        requires_gold_min = 8,
        requires_target_faction = false,
        system_action = "reinforce_campaign",
        narrative = "Reinforcements marched through the night. The war machine devours everything fed to it.",
        consequences = {
            resource_change = {
                { type = "steel", delta = -10, reason = "War reinforcements" },
                { type = "gold", delta = -8, reason = "Resupply costs" },
            },
            cultural_memory_shift = { physical = 2 },
        },
    },

    -- ─── INTRIGUE (continued) ─────────────────────────────────────────────
    {
        id = "suppress_undercurrent",
        category = "intrigue",
        label = "Sever the Pattern",
        description = "The bloodline's hidden tendencies are building toward something dangerous. Act now to disrupt the cycle before it erupts.",
        requires = { axis = "PER_OBS", min = 50 },
        requires_lore_min = 5,
        system_action = "suppress_undercurrent",
        narrative = "The heir studied the patterns in the blood and broke the cycle with deliberate, ruthless intervention.",
        consequences = {
            cultural_memory_shift = { mental = 3 },
            resource_change = { type = "lore", delta = -5, reason = "Research into blood patterns" },
        },
    },

    {
        id = "investigate_rumor",
        category = "intrigue",
        label = "Follow the Whispers",
        description = "Set agents to verify the latest rumors. The truth may arm you — or terrify you.",
        requires = { axis = "PER_OBS", min = 40 },
        requires_lore_min = 3,
        system_action = "investigate_rumor",
        narrative = "Our agents sifted through every whisper and tavern-tale. What they found cannot be unlearned.",
        consequences = {
            resource_change = { type = "lore", delta = -3, reason = "Intelligence gathering" },
            cultural_memory_shift = { mental = 2 },
        },
    },
    {
        id = "exile_courtier",
        category = "intrigue",
        label = "Cast Out the Disloyal",
        description = "Banish a disloyal member of the court. They may vanish quietly — or they may found a shadow lineage sworn to vengeance.",
        requires = { axis = "PER_CRM", min = 40 },
        requires_target_faction = false,
        system_action = "exile_courtier",
        narrative = "The court doors were sealed. When they opened, one seat sat empty. The exiled one was already gone.",
        consequences = {
            cultural_memory_shift = { social = -2, physical = 1 },
            lineage_power_shift = 3,
        },
    },
    {
        id = "forge_relic",
        category = "intrigue",
        label = "Forge an Heirloom",
        description = "Commission the creation of a powerful artifact — a blade, a crown, or a tome — to be wielded by heirs for generations.",
        requires = { axis = "PER_PRI", min = 45 },
        requires_gold_min = 20,
        requires_lore_min = 5,
        requires_generation_min = 5,
        system_action = "forge_relic",
        stat_check = { primary = { trait = "CRE_INN", weight = 1.0 }, secondary = { trait = "MEN_INT", weight = 0.5 }, difficulty = 55 },
        narrative = "The forges burned for a hundred days. What emerged was not merely crafted — it was born.",
        consequences = {
            resource_change = {
                { type = "gold", delta = -20, reason = "Master craftsmen and rare materials" },
                { type = "lore", delta = -5, reason = "Ancient blueprints consumed" },
            },
            cultural_memory_shift = { creative = 3, mental = 1 },
            lineage_power_shift = 8,
        },
        consequences_fail = {
            narrative = "The forges consumed the materials but produced nothing worthy. The heir lacked the vision to guide the craft.",
            resource_change = {
                { type = "gold", delta = -15, reason = "Wasted materials" },
                { type = "lore", delta = -5, reason = "Ancient blueprints consumed" },
            },
            lineage_power_shift = -5,
        },
    },

    -- ─── LEGACY (continued) ───────────────────────────────────────────────
    {
        id = "pursue_dream",
        category = "legacy",
        label = "Chase the Ancestral Dream",
        description = "Dedicate the generation to fulfilling the bloodline's deepest ambition. Shapes the heir and shifts the family's trajectory.",
        requires = { axis = "PER_CUR", min = 35 },
        system_action = "pursue_dream",
        narrative = "The heir bent every waking hour toward the dream that haunts the bloodline's sleep.",
        consequences = {
            cultural_memory_shift = { mental = 2, creative = 2 },
            lineage_power_shift = 5,
        },
    },
    {
        id = "restore_fossil",
        category = "legacy",
        label = "Exhume the Old Deposits",
        description = "The bloodline once excelled in a trait that has since decayed. Pour resources into restoring what was lost.",
        requires = { axis = "PER_PRI", min = 45 },
        requires_lore_min = 8,
        system_action = "restore_fossil",
        narrative = "The archives were opened. The old ways were studied. What the bloodline once was, it may yet become again.",
        consequences = {
            resource_change = { type = "lore", delta = -8, reason = "Ancestral research" },
            lineage_power_shift = 8,
        },
    },
    {
        id = "ride_momentum",
        category = "legacy",
        label = "Ride the Ascending Blood",
        description = "The bloodline is surging in a category across multiple generations. Lean into it — amplify the streak before it fades.",
        requires = nil,
        requires_gold_min = 5,
        system_action = "ride_momentum",
        narrative = "The family leaned into its rising strength. What was a trend became a tradition.",
        consequences = {
            resource_change = { type = "gold", delta = -5, reason = "Investing in the bloodline's momentum" },
            lineage_power_shift = 10,
        },
    },
    {
        id = "forge_discovery",
        category = "legacy",
        label = "Burn the Midnight Lore",
        description = "The heir turns inward, seeking a breakthrough that could change the bloodline's trajectory forever.",
        requires = { axis = "PER_CUR", min = 50 },
        requires_lore_min = 10,
        system_action = "forge_discovery",
        stat_check = { primary = { trait = "MEN_INT", weight = 1.0 }, secondary = { trait = "MEN_FOC", weight = 0.5 }, difficulty = 50 },
        narrative = "Candles burned until dawn. The heir emerged with something new — something that had never existed before.",
        consequences = {
            cultural_memory_shift = { mental = 4, creative = 2 },
            resource_change = { type = "lore", delta = -10, reason = "Research materials" },
        },
        consequences_fail = {
            narrative = "The heir stared at the scrolls until dawn but understood nothing. The lore was wasted on an unready mind.",
            resource_change = { type = "lore", delta = -7, reason = "Wasted research" },
            cultural_memory_shift = { mental = -1 },
        },
    },

    -- ─── FAITH ──────────────────────────────────────────────────────────────
    {
        id = "religious_decree",
        category = "faith",
        label = "Divine Mandate",
        description = "Issue a decree in the name of the faith. Strengthens zealotry and bends the people's will, but plants seeds of fanaticism.",
        requires = { axis = "PER_PRI", min = 50 },
        requires_religion_active = true,
        system_action = "religious_decree",
        narrative = "The decree was read from every pulpit. The faithful trembled and obeyed.",
        consequences = {
            cultural_memory_shift = { social = 3, mental = -2 },
            disposition_changes = { { faction_id = "all", delta = 3 } },
            lineage_power_shift = 8,
        },
    },
    {
        id = "challenge_faith",
        category = "faith",
        label = "Question the Dogma",
        description = "Challenge the religion's core tenets. Risks a schism but opens the door to reformation and new customs.",
        requires = { axis = "PER_CUR", min = 55 },
        personality_blocks = {
            { axis = "PER_LOY", min = 85, reason = "Too devout to question the sacred." },
        },
        requires_religion_active = true,
        system_action = "challenge_faith",
        narrative = "The heir spoke heresy in the temple. Some wept. Some listened. The cracks in the faith deepened.",
        consequences = {
            cultural_memory_shift = { mental = 4, social = -3 },
        },
    },
    {
        id = "enforce_custom",
        category = "faith",
        label = "Enforce the Old Ways",
        description = "Tighten the grip of tradition. Cultural rigidity increases — the bloodline resists change, for better or worse.",
        requires = { axis = "PER_LOY", min = 45 },
        requires_religion_active = true,
        system_action = "enforce_custom",
        narrative = "The old ways were carved deeper into the family's bones. Change would not come easily now.",
        consequences = {
            cultural_memory_shift = { social = 2 },
            lineage_power_shift = 5,
        },
    },
    {
        id = "cultural_reform",
        category = "faith",
        label = "Shatter a Custom",
        description = "Tear down an established tradition. Frees the bloodline from the weight of the past but angers the faithful.",
        requires = { axis = "PER_ADA", min = 55 },
        personality_blocks = {
            { axis = "PER_LOY", min = 85, reason = "Too loyal to the old ways to destroy them." },
            { axis = "PER_OBS", min = 80, reason = "The obsessive cling to every ritual." },
        },
        requires_religion_active = true,
        system_action = "cultural_reform",
        narrative = "What was sacred was declared obsolete. The family trembled at the audacity.",
        consequences = {
            cultural_memory_shift = { creative = 3, social = -4 },
            disposition_changes = { { faction_id = "all", delta = -5 } },
        },
    },
    {
        id = "start_apotheosis",
        category = "faith",
        label = "Begin the Ascension",
        description = "The ultimate act — attempt to transcend mortality itself. Requires a Temple, immense Lore, and an heir of supreme intellect.",
        requires = { axis = "PER_PRI", min = 70 },
        requires_religion_active = true,
        requires_gold_min = 80,
        requires_lore_min = 70,
        requires_generation_min = 50,
        system_action = "start_apotheosis",
        narrative = "The ritual begins. The heir steps beyond the veil between flesh and eternity.",
        consequences = {
            cultural_memory_shift = { mental = 10 },
            resource_change = {
                { type = "gold", delta = -80, reason = "Apotheosis materials" },
                { type = "lore", delta = -70, reason = "Apotheosis sacrifice" },
            },
            lineage_power_shift = 30,
            mutation_triggers = { { type = "mystical_proximity", intensity = 1.0 } },
        },
    },
    {
        id = "canonize_ancestor",
        category = "faith",
        label = "Deification Rite",
        description = "Declare a legendary ancestor as a minor deity. Strengthens the bloodline's divine right but risks a schism if the heir is unworthy.",
        requires = { axis = "PER_PRI", min = 60 },
        requires_has_legend = true,
        requires_religion_active = true,
        requires_generation_min = 10,
        narrative = "The shrines were rededicated. The bloodline's own history became the new divine law.",
        consequences = {
            cultural_memory_shift = { mental = 4, social = 4 },
            lineage_power_shift = 20,
        },
    },
    {
        id = "tithe_to_the_faith",
        category = "faith",
        label = "Votive Offering",
        description = "Donate significant wealth to the priesthood to ensure spiritual stability and lineage favor.",
        requires = { axis = "PER_LOY", min = 40 },
        requires_gold_min = 15,
        requires_religion_active = true,
        narrative = "The temple fires burned bright with our gifts. The priests speak our name with reverence.",
        consequences = {
            cultural_memory_shift = { social = 4 },
            resource_change = { type = "gold", delta = -15, reason = "Sacred tithe" },
            disposition_changes = { { faction_id = "all", delta = 2 } },
        },
    },

    -- ─── LEGACY (echoes) ──────────────────────────────────────────────────
    {
        id = "commune_ancestors",
        category = "legacy",
        label = "Commune with the Dead",
        description = "The heir enters the ancestral vault and invokes the ghosts of legendary forebears. Their wisdom — or their madness — flows into the blood.",
        requires = { axis = "PER_PRI", min = 40 },
        requires_generation_min = 5,
        system_action = "commune_ancestors",
        narrative = "The candles were lit. The names were spoken. And something answered.",
        consequences = {
            cultural_memory_shift = { mental = 2 },
            lineage_power_shift = 5,
        },
    },

    -- ─── PROVISIONING ─────────────────────────────────────────────────────
    {
        id = "feast_of_tribute",
        category = "diplomacy",
        label = "The Feast of Tribute",
        description = "Slaughter the herds and fill the tables. Feed a rival house until they owe you a debt measured in stomachs, not coin.",
        requires = { axis = "PER_ADA", min = 40 },
        requires_grain_min = 15,
        requires_target_faction = true,
        narrative = "The tables groaned under the weight of our generosity. They ate, and they remembered who fed them.",
        consequences = {
            disposition_changes = { { faction_id = "_target", delta = 18 } },
            resource_change = { type = "grain", delta = -15, reason = "Feast provisions" },
            cultural_memory_shift = { social = 3 },
        },
    },
    {
        id = "granary_reserve",
        category = "legacy",
        label = "Seal the Granaries",
        description = "Lock away a generation's surplus against the famines that always come. Costs dearly now. Saves everything later.",
        requires = { axis = "PER_OBS", min = 45 },
        requires_grain_min = 20,
        requires_target_faction = false,
        narrative = "The granaries were sealed with iron and wax. The family will eat while the world starves.",
        consequences = {
            resource_change = { type = "grain", delta = -20, reason = "Strategic reserves" },
            cultural_memory_shift = { mental = 2, physical = 1 },
            lineage_power_shift = 8,
        },
        system_action = "seal_granaries",
    },
    {
        id = "feed_the_faithful",
        category = "faith",
        label = "Feed the Faithful",
        description = "Open the granaries to the faithful. Full bellies breed zealotry more reliably than sermons.",
        requires = { axis = "PER_LOY", min = 40 },
        requires_grain_min = 12,
        requires_religion_active = true,
        requires_target_faction = false,
        narrative = "The faithful were fed. They called it a miracle. We called it a down payment.",
        consequences = {
            resource_change = { type = "grain", delta = -12, reason = "Distributed to the faithful" },
            cultural_memory_shift = { social = 4 },
            disposition_changes = { { faction_id = "all", delta = 3 } },
            lineage_power_shift = 5,
        },
    },
    {
        id = "provision_expedition",
        category = "intrigue",
        label = "Provision an Expedition",
        description = "Fund and supply a long-range scouting party. What they find could reshape the bloodline's trajectory.",
        requires = { axis = "PER_CUR", min = 45 },
        requires_grain_min = 10,
        requires_gold_min = 8,
        requires_target_faction = false,
        system_action = "provision_expedition",
        stat_check = { primary = { trait = "MEN_PER", weight = 1.0 }, secondary = { trait = "PHY_END", weight = 0.5 }, difficulty = 38 },
        narrative = "The wagons left at dawn, heavy with grain and gold. They carried our curiosity into the unknown.",
        consequences = {
            resource_change = {
                { type = "grain", delta = -10, reason = "Expedition supplies" },
                { type = "gold", delta = -8, reason = "Expedition wages" },
            },
            cultural_memory_shift = { mental = 3, creative = 1 },
        },
        consequences_fail = {
            narrative = "The expedition was poorly planned. The scouts returned empty-handed, having consumed the supplies for nothing.",
            resource_change = {
                { type = "grain", delta = -10, reason = "Expedition supplies (wasted)" },
                { type = "gold", delta = -5, reason = "Expedition wages" },
            },
        },
    },
    {
        id = "arm_the_holdings",
        category = "warfare",
        label = "Arm the Holdings",
        description = "Distribute weapons and armor to every domain. The peasants become militia. The militia become a threat.",
        requires = { axis = "PER_BLD", min = 35 },
        requires_steel_min = 12,
        requires_target_faction = false,
        narrative = "Every farm received a blade. Every village, a shield. The holdings are no longer helpless.",
        consequences = {
            resource_change = { type = "steel", delta = -12, reason = "Arming the domains" },
            cultural_memory_shift = { physical = 4, social = -1 },
            lineage_power_shift = 8,
        },
        system_action = "arm_holdings",
    },
    {
        id = "gift_of_iron",
        category = "diplomacy",
        label = "Gift of Iron",
        description = "Send forged steel to a rival house. A gesture of strength, not charity — they will remember who armed them.",
        requires = { axis = "PER_LOY", min = 40 },
        requires_steel_min = 10,
        requires_target_faction = true,
        narrative = "Crates of weapons arrived at their gate, stamped with our seal. Let them fight their wars with our steel.",
        consequences = {
            disposition_changes = { { faction_id = "_target", delta = 15 } },
            resource_change = { type = "steel", delta = -10, reason = "Diplomatic arms gift" },
            cultural_memory_shift = { physical = 1, social = 2 },
        },
    },
    {
        id = "found_settlement",
        category = "legacy",
        label = "Plant a New Root",
        description = "Spend everything — grain, gold, steel — to carve a new holding from the wilderness. A generation's wealth for a legacy that outlasts them all.",
        requires = { axis = "PER_PRI", min = 50 },
        requires_grain_min = 15,
        requires_gold_min = 20,
        requires_steel_min = 10,
        requires_target_faction = false,
        requires_generation_min = 8,
        system_action = "found_settlement",
        stat_check = { primary = { trait = "PHY_END", weight = 1.0 }, secondary = { trait = "SOC_LDR", weight = 0.5 }, tertiary = { trait = "MEN_STR", weight = 0.25 }, difficulty = 60 },
        narrative = "The first stones were laid in untamed land. A new root reaches into the earth.",
        consequences = {
            resource_change = {
                { type = "grain", delta = -15, reason = "Settler provisions" },
                { type = "gold", delta = -20, reason = "Settlement funding" },
                { type = "steel", delta = -10, reason = "Construction and tools" },
            },
            cultural_memory_shift = { physical = 2, creative = 2 },
            lineage_power_shift = 15,
        },
        consequences_fail = {
            narrative = "The settlers starved. The walls fell. The heir lacked the endurance to build something from nothing.",
            resource_change = {
                { type = "grain", delta = -15, reason = "Settler provisions (lost)" },
                { type = "gold", delta = -12, reason = "Settlement funding (lost)" },
                { type = "steel", delta = -5, reason = "Tools abandoned" },
            },
            lineage_power_shift = -10,
        },
    },
    {
        id = "specialize_holding",
        category = "legacy",
        label = "Develop the Estate",
        description = "Pour lore and gold into a holding, shaping it into something greater — a war college, scriptorium, artisan guild, or diplomatic quarter.",
        requires = { axis = "PER_OBS", min = 35 },
        requires_lore_min = 8,
        requires_gold_min = 10,
        requires_holdings_min = 1,
        requires_target_holding = true,
        requires_target_faction = false,
        system_action = "specialize_holding",
        stat_check = { primary = { trait = "MEN_INT", weight = 1.0 }, secondary = { trait = "MEN_ANA", weight = 0.5 }, difficulty = 45 },
        narrative = "The heir studied the holding's nature and shaped it with purpose. Stone by stone, the domain became something more.",
        consequences = {
            resource_change = {
                { type = "lore", delta = -8, reason = "Development planning" },
                { type = "gold", delta = -10, reason = "Construction and specialists" },
            },
            cultural_memory_shift = { mental = 1, creative = 1 },
            lineage_power_shift = 5,
        },
        consequences_fail = {
            narrative = "The plans were drawn, the gold was spent, but the work collapsed. The holding remained unchanged.",
            resource_change = {
                { type = "lore", delta = -4, reason = "Planning wasted" },
                { type = "gold", delta = -6, reason = "Construction abandoned" },
            },
        },
    },
    {
        id = "scorched_earth",
        category = "warfare",
        label = "Scorched Earth",
        description = "Burn your own surplus to deny it to the enemy. The fields turn to ash. The invaders find nothing worth taking.",
        requires = { axis = "PER_BLD", min = 55 },
        personality_blocks = {
            { axis = "PER_OBS", min = 85, reason = "Cannot destroy what they've spent generations building." },
        },
        requires_grain_min = 20,
        requires_condition = "war",
        requires_target_faction = false,
        narrative = "The fires burned for three days. Our grain, our fields, our future — all sacrificed so the enemy would starve before we did.",
        consequences = {
            resource_change = { type = "grain", delta = -20, reason = "Scorched earth denial" },
            cultural_memory_shift = { physical = 3, social = -3 },
            lineage_power_shift = 10,
            moral_act = { act_id = "sacrifice", description = "Burned the bloodline's own grain to deny the enemy" },
        },
    },

    -- ─── MORALITY & FAITH ──────────────────────────────────────────────────
    {
        id = "offer_sanctuary",
        category = "diplomacy",
        label = "Offer Sanctuary",
        description = "Open the gates to refugees, exiles, and the desperate. Costs grain and gold, but earns the devotion of the dispossessed and the respect of the righteous.",
        requires_morality_min = 20,
        requires_grain_min = 10,
        requires_gold_min = 5,
        requires_target_faction = false,
        narrative = "The gates opened. The wretched poured in, clutching children and bundles of nothing. The bloodline had less. The bloodline was more.",
        consequences = {
            resource_change = {
                { type = "grain", delta = -10, reason = "Feeding refugees" },
                { type = "gold", delta = -5, reason = "Refugee provisions" },
            },
            disposition_changes = { { faction_id = "all", delta = 8 } },
            cultural_memory_shift = { social = 4 },
            lineage_power_shift = 8,
            moral_act = { act_id = "charity", description = "Opened the gates to refugees and the dispossessed" },
        },
    },
    {
        id = "blood_market",
        category = "intrigue",
        label = "The Flesh Ledger",
        description = "Sell prisoners, debtors, and the inconvenient into labor camps abroad. The gold flows freely. The soul does not.",
        requires_morality_max = -10,
        requires = { axis = "PER_CRM", min = 55 },
        requires_target_faction = false,
        narrative = "The prisoners were marched to the docks in chains. Gold changed hands. Names were erased from the record. The bloodline grew richer and darker.",
        consequences = {
            resource_change = { type = "gold", delta = 20, reason = "Human trafficking revenue" },
            cultural_memory_shift = { social = -6, physical = 1 },
            lineage_power_shift = -5,
            moral_act = { act_id = "oppression", description = "Sold prisoners and debtors into forced labor" },
            disposition_changes = { { faction_id = "all", delta = -5 } },
        },
    },
    {
        id = "holy_inquisition",
        category = "faith",
        label = "The Inquisition",
        description = "Root out heretics and doubters. The faith demands purity. The pyres demand fuel.",
        requires_religion_active = true,
        requires_zealotry_min = 55,
        requires_morality_max = 30,
        requires = { axis = "PER_OBS", min = 50 },
        requires_target_faction = false,
        stat_check = { primary = { trait = "SOC_INF", weight = 1.0 }, secondary = { trait = "MEN_WIL", weight = 0.5 }, difficulty = 40 },
        narrative = "The inquisitors moved through the holdings with torch and question. The smoke rose for days.",
        consequences = {
            cultural_memory_shift = { mental = -3, social = -4 },
            lineage_power_shift = 10,
            moral_act = { act_id = "oppression", description = "Purged heretics through inquisition" },
            disposition_changes = { { faction_id = "all", delta = -8 } },
        },
        consequences_fail = {
            narrative = "The inquisition overreached. The people turned on the inquisitors. The faith was weakened, not strengthened.",
            cultural_memory_shift = { social = -2 },
            lineage_power_shift = -8,
            moral_act = { act_id = "oppression", description = "Failed inquisition turned the people against the faith" },
        },
    },
    {
        id = "sacred_pilgrimage",
        category = "faith",
        label = "The Sacred Walk",
        description = "Send the heir on a journey to the faith's holiest sites. They return changed — or they do not return at all.",
        requires_religion_active = true,
        requires_zealotry_min = 35,
        requires_morality_min = 10,
        requires_gold_min = 10,
        requires_target_faction = false,
        stat_check = { primary = { trait = "PHY_END", weight = 1.0 }, secondary = { trait = "MEN_WIL", weight = 0.5 }, difficulty = 35 },
        narrative = "The heir walked the old roads with nothing but faith and worn boots. What they found cannot be written in any ledger.",
        consequences = {
            resource_change = { type = "gold", delta = -10, reason = "Pilgrimage expenses" },
            cultural_memory_shift = { mental = 3, social = 2 },
            lineage_power_shift = 5,
            moral_act = { act_id = "honoring_oath", description = "Completed a sacred pilgrimage" },
        },
        consequences_fail = {
            narrative = "The heir returned early, broken by the road. The faithful whispered of unworthiness.",
            resource_change = { type = "gold", delta = -10, reason = "Pilgrimage expenses (wasted)" },
            cultural_memory_shift = { physical = -2 },
            lineage_power_shift = -3,
        },
    },
    {
        id = "mandate_of_mercy",
        category = "diplomacy",
        label = "Decree of Mercy",
        description = "Formally forbid cruelty within the bloodline's domains. The strong lose a weapon. The weak gain a shield.",
        requires_morality_min = 40,
        requires = { axis = "PER_CRM", max = 45 },
        requires_target_faction = false,
        narrative = "The decree was carved into the gatehouse stone: no torture, no enslavement, no cruelty without consequence. The world watched to see if the bloodline meant it.",
        consequences = {
            disposition_changes = { { faction_id = "all", delta = 10 } },
            cultural_memory_shift = { social = 5, physical = -2 },
            lineage_power_shift = 12,
            moral_act = { act_id = "protection", description = "Decreed mercy as law within the bloodline's domains" },
        },
    },
    {
        id = "zealots_tithe",
        category = "faith",
        label = "The Zealot's Tax",
        description = "Demand the faithful give everything — grain, gold, steel — to the cause. They will. That is what faith is for.",
        requires_religion_active = true,
        requires_zealotry_min = 65,
        requires_target_faction = false,
        narrative = "The faithful emptied their pockets, their granaries, their forges. They called it devotion. The ledger called it revenue.",
        consequences = {
            resource_change = {
                { type = "grain", delta = 8, reason = "Zealot tithes (grain)" },
                { type = "gold", delta = 8, reason = "Zealot tithes (gold)" },
                { type = "steel", delta = 4, reason = "Zealot tithes (steel)" },
            },
            cultural_memory_shift = { social = -3 },
            moral_act = { act_id = "exploitation", description = "Extracted resources from the faithful through religious pressure" },
        },
    },

    -- ─── RESOURCE CONVERSION ────────────────────────────────────────────────
    {
        id = "sell_grain_stores",
        category = "diplomacy",
        label = "Sell the Surplus",
        description = "Convert excess grain into gold on the open market. The granaries empty, the coffers fill.",
        requires = nil,
        requires_grain_min = 18,
        requires_target_faction = false,
        narrative = "Wagons heavy with grain rolled out through the gates. They returned light, but laden with coin.",
        consequences = {
            resource_change = {
                { type = "grain", delta = -18, reason = "Grain sold at market" },
                { type = "gold", delta = 14, reason = "Grain sale revenue" },
            },
            cultural_memory_shift = { social = 1 },
        },
    },
    {
        id = "commission_scholars",
        category = "legacy",
        label = "Endow the Scholars",
        description = "Hire scribes, tutors, and archivists. Gold buys knowledge. Knowledge buys survival.",
        requires = { axis = "PER_CUR", min = 35 },
        requires_gold_min = 18,
        requires_target_faction = false,
        narrative = "The scholars arrived with their ink-stained fingers and their impossible promises. What they wrote will outlast us all.",
        consequences = {
            resource_change = {
                { type = "gold", delta = -18, reason = "Scholar stipends" },
                { type = "lore", delta = 10, reason = "Commissioned research" },
            },
            cultural_memory_shift = { mental = 2 },
        },
    },
    {
        id = "arm_the_peasants",
        category = "warfare",
        label = "Reap and Reforge",
        description = "Melt down plowshares and scythes into blades and spear-tips. The harvest suffers; the armory does not.",
        requires = { axis = "PER_BLD", min = 40 },
        requires_grain_min = 12,
        requires_target_faction = false,
        narrative = "The smiths worked the plowshares into crude blades. The fields would lie fallow, but the family would not lie defenseless.",
        consequences = {
            resource_change = {
                { type = "grain", delta = -12, reason = "Farm equipment melted down" },
                { type = "steel", delta = 8, reason = "Reforged agricultural tools" },
            },
            cultural_memory_shift = { physical = 2, creative = -1 },
        },
    },
    {
        id = "melt_down_relics",
        category = "intrigue",
        label = "Melt the Heirlooms",
        description = "Sell ancestral trinkets, melt ornamental steel, and pawn the family silver. Dignity costs more than gold.",
        requires = nil,
        requires_steel_min = 10,
        requires_target_faction = false,
        narrative = "The old swords and silver plate were sold at market. What the ancestors forged, the heir spent.",
        consequences = {
            resource_change = {
                { type = "steel", delta = -10, reason = "Ancestral steel liquidated" },
                { type = "gold", delta = 12, reason = "Steel and relics sold" },
            },
            cultural_memory_shift = { creative = -1 },
            lineage_power_shift = -3,
        },
    },
    {
        id = "trade_steel_provisions",
        category = "diplomacy",
        label = "Steel for Bread",
        description = "Trade forged steel to neighboring farms and villages in exchange for grain. The strong arm the weak; the weak feed the strong.",
        requires = nil,
        requires_steel_min = 10,
        requires_target_faction = false,
        narrative = "Blades for bushels. The age-old bargain that keeps empires fed and villages armed.",
        consequences = {
            resource_change = {
                { type = "steel", delta = -10, reason = "Traded to farmsteads" },
                { type = "grain", delta = 14, reason = "Grain from armed villages" },
            },
            cultural_memory_shift = { social = 1 },
        },
    },

    -- ─── SYSTEM ─────────────────────────────────────────────────────────────
    {
        id = "consolidate",
        category = "legacy",
        label = "Balance the Books",
        description = "Step back from active rule. Listen to the whispers of the blood and gather the family's strength.",
        requires = nil,
        requires_target_faction = false,
        narrative = "The world continued to spin, but the bloodline remained still, watchful and ready.",
        consequences = {
            resource_change = {
                { type = "gold", delta = 8, reason = "Reduced court spending" },
                { type = "lore", delta = 3, reason = "Deep study" }
            },
            lineage_power_shift = 5,
            cultural_memory_shift = { mental = 1 },
        },
    },
}
